// Auto-generated enums for comunas grouped by region
// Enum keys are ASCII-normalized identifiers; values preserve display names (including accents)

export enum ComunasAricaYParinacota {
  ARICA = 'Arica',
  CAMARONES = 'Camarones',
  PUTRE = 'Putre',
  GENERAL_LAGOS = 'General Lagos',
}

export enum ComunasTarapaca {
  IQUIQUE = 'Iquique',
  ALTO_HOSPICIO = 'Alto Hospicio',
  POZO_ALMONTE = 'Pozo Almonte',
  CAMINA = 'Camiña',
  COLCHANE = 'Colchane',
  HUARA = 'Huara',
  PICA = 'Pica',
}

export enum ComunasAntofagasta {
  ANTOFAGASTA = 'Antofagasta',
  MEJILLONES = 'Mejillones',
  SIERRA_GORDA = 'Sierra Gorda',
  TALTAL = 'Taltal',
  CALAMA = 'Calama',
  OLLAGUE = 'Ollagüe',
  SAN_PEDRO_DE_ATACAMA = 'San Pedro de Atacama',
  TOCOPILLA = 'Tocopilla',
  MARIA_ELENA = 'María Elena',
}

export enum ComunasAtacama {
  COPIAPO = 'Copiapó',
  CALDERA = 'Caldera',
  TIERRA_AMARILLA = 'Tierra Amarilla',
  CHANARAL = 'Chañaral',
  DIEGO_DE_ALMAGRO = 'Diego de Almagro',
  VALLENAR = 'Vallenar',
  HUASCO = 'Huasco',
  FREIRINA = 'Freirina',
  ALTO_DEL_CARMEN = 'Alto del Carmen',
}

export enum ComunasCoquimbo {
  LA_SERENA = 'La Serena',
  COQUIMBO = 'Coquimbo',
  ANDACOLLO = 'Andacollo',
  LA_HIGUERA = 'La Higuera',
  PAIGUANO = 'Paiguano',
  VICUNA = 'Vicuña',
  ILLAPEL = 'Illapel',
  CANELA = 'Canela',
  LOS_VILOS = 'Los Vilos',
  SALAMANCA = 'Salamanca',
  OVALLE = 'Ovalle',
  COMBARBALA = 'Combarbalá',
  MONTE_PATRIA = 'Monte Patria',
  PUNITAQUI = 'Punitaqui',
  RIO_HURTADO = 'Río Hurtado',
}

export enum ComunasValparaiso {
  VALPARAISO = 'Valparaíso',
  CASABLANCA = 'Casablanca',
  CONCON = 'Concón',
  JUAN_FERNANDEZ = 'Juan Fernández',
  PUCHUNCAVI = 'Puchuncaví',
  QUINTERO = 'Quintero',
  VINA_DEL_MAR = 'Viña del Mar',
  QUILPUE = 'Quilpué',
  LIMACHE = 'Limache',
  OLMUE = 'Olmué',
  VILLA_ALEMANA = 'Villa Alemana',
  ISLA_DE_PASCUA = 'Isla de Pascua',
  LOS_ANDES = 'Los Andes',
  CALLE_LARGA = 'Calle Larga',
  RINCONADA = 'Rinconada',
  SAN_ESTEBAN = 'San Esteban',
  LA_LIGUA = 'La Ligua',
  CABILDO = 'Cabildo',
  PAPUDO = 'Papudo',
  PETORCA = 'Petorca',
  ZAPALLAR = 'Zapallar',
  QUILLOTA = 'Quillota',
  LA_CALERA = 'La Calera',
  LA_CRUZ = 'La Cruz',
  NOGALES = 'Nogales',
  SAN_ANTONIO = 'San Antonio',
  ALGARROBO = 'Algarrobo',
  CARTAGENA = 'Cartagena',
  EL_QUISCO = 'El Quisco',
  EL_TABO = 'El Tabo',
  SANTO_DOMINGO = 'Santo Domingo',
  SAN_FELIPE = 'San Felipe',
  CATEMU = 'Catemu',
  LLAILLAY = 'Llaillay',
  PANQUEHUE = 'Panquehue',
  PUTAENDO = 'Putaendo',
  SANTA_MARIA = 'Santa María',
}

export enum ComunasMetropolitana {
  CERRILLOS = 'Cerrillos',
  CERRO_NAVIA = 'Cerro Navia',
  CONCHALI = 'Conchalí',
  EL_BOSQUE = 'El Bosque',
  ESTACION_CENTRAL = 'Estación Central',
  HUECHURABA = 'Huechuraba',
  INDEPENDENCIA = 'Independencia',
  LA_CISTERNA = 'La Cisterna',
  LA_FLORIDA = 'La Florida',
  LA_GRANJA = 'La Granja',
  LA_PINTANA = 'La Pintana',
  LA_REINA = 'La Reina',
  LAS_CONDES = 'Las Condes',
  LO_BARNECHEA = 'Lo Barnechea',
  LO_ESPEJO = 'Lo Espejo',
  LO_PRADO = 'Lo Prado',
  MACUL = 'Macul',
  MAIPU = 'Maipú',
  NUNOA = 'Ñuñoa',
  PEDRO_AGUIRRE_CERDA = 'Pedro Aguirre Cerda',
  PENALOLEN = 'Peñalolén',
  PROVIDENCIA = 'Providencia',
  PUDAHUEL = 'Pudahuel',
  QUILICURA = 'Quilicura',
  QUINTA_NORMAL = 'Quinta Normal',
  RECOLETA = 'Recoleta',
  RENCA = 'Renca',
  SAN_JOAQUIN = 'San Joaquín',
  SAN_MIGUEL = 'San Miguel',
  SAN_RAMON = 'San Ramón',
  VITACURA = 'Vitacura',
  PUENTE_ALTO = 'Puente Alto',
  PIRQUE = 'Pirque',
  SAN_JOSE_DE_MAIPO = 'San José de Maipo',
  COLINA = 'Colina',
  LAMPA = 'Lampa',
  TIL_TIL = 'Tiltil',
  SAN_BERNARDO = 'San Bernardo',
  BUIN = 'Buin',
  CALERA_DE_TANGO = 'Calera de Tango',
  PAINE = 'Paine',
  MELIPILLA = 'Melipilla',
  ALHUE = 'Alhué',
  CURACAVI = 'Curacaví',
  MARIA_PINTO = 'María Pinto',
  SAN_PEDRO = 'San Pedro',
  TALAGANTE = 'Talagante',
  EL_MONTE = 'El Monte',
  ISLA_DE_MAIPO = 'Isla de Maipo',
  PADRE_HURTADO = 'Padre Hurtado',
  PENAFLOR = 'Peñaflor',
}

export enum ComunasOhiggins {
  RANCAGUA = 'Rancagua',
  CODEGUA = 'Codegua',
  COINCO = 'Coinco',
  COLTAUCO = 'Coltauco',
  DONIHUE = 'Doñihue',
  GRANEROS = 'Graneros',
  LAS_CABRAS = 'Las Cabras',
  MACHALI = 'Machalí',
  MALLOA = 'Malloa',
  MOSTAZAL = 'Mostazal',
  OLIVAR = 'Olivar',
  PEUMO = 'Peumo',
  PICHIDEGUA = 'Pichidegua',
  QUINTA_DE_TILCOCO = 'Quinta de Tilcoco',
  RENGO = 'Rengo',
  REQUINOA = 'Requínoa',
  SAN_VICENTE = 'San Vicente',
  PICHILEMU = 'Pichilemu',
  LA_Estrella = 'La Estrella',
  LITUECHE = 'Litueche',
  MARCHIHUE = 'Marchihue',
  NAVIDAD = 'Navidad',
  PAREDONES = 'Paredones',
  SAN_FERNANDO = 'San Fernando',
  CHEPICA = 'Chépica',
  CHIMBARONGO = 'Chimbarongo',
  LOLOL = 'Lolol',
  NANCAGUA = 'Nancagua',
  PAMILLA = 'Palmilla',
  PERALILLO = 'Peralillo',
  PLACILLA = 'Placilla',
  PUMANQUE = 'Pumanque',
  SANTA_CRUZ = 'Santa Cruz',
}

export enum ComunasMaule {
  TALCA = 'Talca',
  CONSTITUCION = 'Constitución',
  CUREPTO = 'Curepto',
  EMPEDRADO = 'Empedrado',
  MAULE = 'Maule',
  PELARCO = 'Pelarco',
  PENCAHUE = 'Pencahue',
  RIO_CLARO = 'Río Claro',
  SAN_CLEMENTE = 'San Clemente',
  SAN_RAFAEL = 'San Rafael',
  CAUQUENES = 'Cauquenes',
  CHANCO = 'Chanco',
  PELLUHUE = 'Pelluhue',
  CURICO = 'Curicó',
  HUALANE = 'Hualañé',
  LICANTEN = 'Licantén',
  MOLINA = 'Molina',
  RAUCO = 'Rauco',
  ROMERAL = 'Romeral',
  SAGRADA_FAMILIA = 'Sagrada Familia',
  TENO = 'Teno',
  VICHUQUEN = 'Vichuquén',
  LINARES = 'Linares',
  COLBUN = 'Colbún',
  LONGAVI = 'Longaví',
  PARRAL = 'Parral',
  RETIRO = 'Retiro',
  SAN_JAVIER = 'San Javier',
  VILLA_ALEGRE = 'Villa Alegre',
  YERBAS_BUENAS = 'Yerbas Buenas',
}

export enum ComunasÑuble {
  CHILLAN = 'Chillán',
  BULNES = 'Bulnes',
  COBQUECURA = 'Cobquecura',
  COELEMU = 'Coelemu',
  COIHUECO = 'Coihueco',
  EL_CARMEN = 'El Carmen',
  NINHUE = 'Ninhue',
  NIQUEN = 'Ñiquén',
  PEMUCO = 'Pemuco',
  PINTO = 'Pinto',
  PORTEZUELO = 'Portezuelo',
  QUILLON = 'Quillón',
  QUIRIHUE = 'Quirihue',
  RANQUIL = 'Ránquil',
  SAN_CARLOS = 'San Carlos',
  SAN_FABIAN = 'San Fabián',
  SAN_IGNACIO = 'San Ignacio',
  SAN_NICOLAS = 'San Nicolás',
  TREGUACO = 'Treguaco',
  YUNGAY = 'Yungay',
}

export enum ComunasBiobio {
  CONCEPCION = 'Concepción',
  CORONEL = 'Coronel',
  CHIGUAYANTE = 'Chiguayante',
  FLORIDA = 'Florida',
  HUALQUI = 'Hualqui',
  LOTA = 'Lota',
  PENCO = 'Penco',
  SAN_PEDRO_DE_LA_PAZ = 'San Pedro de la Paz',
  SANTA_JUANA = 'Santa Juana',
  TALCAHUANO = 'Talcahuano',
  TOME = 'Tomé',
  HUALPEN = 'Hualpén',
  LEBU = 'Lebu',
  ARAUCO = 'Arauco',
  CANETE = 'Cañete',
  CONTULMO = 'Contulmo',
  CURANILAHUE = 'Curanilahue',
  LOS_ALAMOS = 'Los Álamos',
  TIRUA = 'Tirúa',
  LOS_ANGELES = 'Los Ángeles',
  ANTUCO = 'Antuco',
  CABRERO = 'Cabrero',
  LAJA = 'Laja',
  MULCHEN = 'Mulchén',
  NACIMIENTO = 'Nacimiento',
  NEGRETE = 'Negrete',
  QUILACO = 'Quilaco',
  QUILLECO = 'Quilleco',
  SAN_ROSENDO = 'San Rosendo',
  SANTA_BARBARA = 'Santa Bárbara',
  TUCAPEL = 'Tucapel',
  YUMBEL = 'Yumbel',
  ALTO_BIOBIO = 'Alto Biobío',
}

export enum ComunasAraucania {
  TEMUCO = 'Temuco',
  CARAHUE = 'Carahue',
  CUNCO = 'Cunco',
  CURARREHUE = 'Curarrehue',
  FREIRE = 'Freire',
  GALVARINO = 'Galvarino',
  GORBEA = 'Gorbea',
  LAUTARO = 'Lautaro',
  LONCOCHE = 'Loncoche',
  MELIPEUCO = 'Melipeuco',
  NUEVA_IMPERIAL = 'Nueva Imperial',
  PADRE_LAS_CASAS = 'Padre Las Casas',
  PERQUENCO = 'Perquenco',
  PITRUFQUEN = 'Pitrufquén',
  PUCON = 'Pucón',
  SAAVEDRA = 'Saavedra',
  TEODORO_SCHMIDT = 'Teodoro Schmidt',
  TOLTEN = 'Toltén',
  VILCUN = 'Vilcún',
  VILLARRICA = 'Villarrica',
  CHOLCHOL = 'Cholchol',
  ANGOL = 'Angol',
  COLLIPULLI = 'Collipulli',
  ERCILLA = 'Ercilla',
  LONQUIMAY = 'Lonquimay',
  LOS_SAUCES = 'Los Sauces',
  LUMACO = 'Lumaco',
  PUREN = 'Purén',
  RENAICO = 'Renaico',
  TRAIGUEN = 'Traiguén',
  VICTORIA = 'Victoria',
}

export enum ComunasLosRios {
  VALDIVIA = 'Valdivia',
  CORRAL = 'Corral',
  LANCO = 'Lanco',
  LOS_LAGOS = 'Los Lagos',
  MAFIL = 'Máfil',
  MARIQUINA = 'Mariquina',
  PAILLACO = 'Paillaco',
  PANGUIPULLI = 'Panguipulli',
  LA_UNION = 'La Unión',
  FUTRONO = 'Futrono',
  LAGO_RANCO = 'Lago Ranco',
  RIO_BUENO = 'Río Bueno',
}

export enum ComunasLosLagos {
  PUERTO_MONTT = 'Puerto Montt',
  CALBUCO = 'Calbuco',
  COCHAMO = 'Cochamó',
  FRESIA = 'Fresia',
  FRUTILLAR = 'Frutillar',
  LOS_MUERMOS = 'Los Muermos',
  LLANQUIHUE = 'Llanquihue',
  MAULLIN = 'Maullín',
  PUERTO_VARAS = 'Puerto Varas',
  CASTRO = 'Castro',
  CHONCHI = 'Chonchi',
  CURACO_DE_VELEZ = 'Curaco de Vélez',
  DALCAHUE = 'Dalcahue',
  PUQUELDON = 'Puqueldón',
  QUEILEN = 'Queilén',
  QUELLON = 'Quellón',
  QUEMCHI = 'Quemchi',
  QUINCHAO = 'Quinchao',
  OSORNO = 'Osorno',
  PUERTO_OCTAY = 'Puerto Octay',
  PURRANQUE = 'Purranque',
  PUYEHUE = 'Puyehue',
  RIO_NEGRO = 'Río Negro',
  SAN_JUAN_DE_LA_COSTA = 'San Juan de la Costa',
  SAN_PABLO = 'San Pablo',
}

export enum ComunasAysen {
  COYHAIQUE = 'Coyhaique',
  LAGO_VERDE = 'Lago Verde',
  AYSEN = 'Aysén',
  CISNES = 'Cisnes',
  GUAITECAS = 'Guaitecas',
  RIO_IBANEZ = 'Río Ibáñez',
  CHILE_CHICO = 'Chile Chico',
  COCHRANE = 'Cochrane',
  OHIGGINS = "O'Higgins",
  TORTEL = 'Tortel',
}

export enum ComunasMagallanes {
  PUNTA_ARENAS = 'Punta Arenas',
  LAGUNA_BLANCA = 'Laguna Blanca',
  RIO_VERDE = 'Río Verde',
  SAN_GREGORIO = 'San Gregorio',
  CABO_DE_HORNOS = 'Cabo de Hornos',
  ANTARTICA = 'Antártica',
  PORVENIR = 'Porvenir',
  PRIMAVERA = 'Primavera',
  TIMAUKEL = 'Timaukel',
  NATALES = 'Natales',
  TORRES_DEL_PAINE = 'Torres del Paine',
}

// Combined export types for convenience
export type ComunaEnums =
  | ComunasAricaYParinacota
  | ComunasTarapaca
  | ComunasAntofagasta
  | ComunasAtacama
  | ComunasCoquimbo
  | ComunasValparaiso
  | ComunasMetropolitana
  | ComunasOhiggins
  | ComunasMaule
  | ComunasÑuble
  | ComunasBiobio
  | ComunasAraucania
  | ComunasLosRios
  | ComunasLosLagos
  | ComunasAysen
  | ComunasMagallanes;

export const ALL_COMUNAS: string[] = [
  // build a flat list by repeating values; keep in sync with enums above
  // Arica y Parinacota
  'Arica',
  'Camarones',
  'Putre',
  'General Lagos',
  // Tarapacá
  'Iquique',
  'Alto Hospicio',
  'Pozo Almonte',
  'Camiña',
  'Colchane',
  'Huara',
  'Pica',
  // Antofagasta
  'Antofagasta',
  'Mejillones',
  'Sierra Gorda',
  'Taltal',
  'Calama',
  'Ollagüe',
  'San Pedro de Atacama',
  'Tocopilla',
  'María Elena',
  // Atacama
  'Copiapó',
  'Caldera',
  'Tierra Amarilla',
  'Chañaral',
  'Diego de Almagro',
  'Vallenar',
  'Huasco',
  'Freirina',
  'Alto del Carmen',
  // Coquimbo
  'La Serena',
  'Coquimbo',
  'Andacollo',
  'La Higuera',
  'Paiguano',
  'Vicuña',
  'Illapel',
  'Canela',
  'Los Vilos',
  'Salamanca',
  'Ovalle',
  'Combarbalá',
  'Monte Patria',
  'Punitaqui',
  'Río Hurtado',
  // Valparaíso
  'Valparaíso',
  'Casablanca',
  'Concón',
  'Juan Fernández',
  'Puchuncaví',
  'Quintero',
  'Viña del Mar',
  'Quilpué',
  'Limache',
  'Olmué',
  'Villa Alemana',
  'Isla de Pascua',
  'Los Andes',
  'Calle Larga',
  'Rinconada',
  'San Esteban',
  'La Ligua',
  'Cabildo',
  'Papudo',
  'Petorca',
  'Zapallar',
  'Quillota',
  'La Calera',
  'La Cruz',
  'Nogales',
  'San Antonio',
  'Algarrobo',
  'Cartagena',
  'El Quisco',
  'El Tabo',
  'Santo Domingo',
  'San Felipe',
  'Catemu',
  'Llaillay',
  'Panquehue',
  'Putaendo',
  'Santa María',
  // Metropolitana
  'Cerrillos',
  'Cerro Navia',
  'Conchalí',
  'El Bosque',
  'Estación Central',
  'Huechuraba',
  'Independencia',
  'La Cisterna',
  'La Florida',
  'La Granja',
  'La Pintana',
  'La Reina',
  'Las Condes',
  'Lo Barnechea',
  'Lo Espejo',
  'Lo Prado',
  'Macul',
  'Maipú',
  'Ñuñoa',
  'Pedro Aguirre Cerda',
  'Peñalolén',
  'Providencia',
  'Pudahuel',
  'Quilicura',
  'Quinta Normal',
  'Recoleta',
  'Renca',
  'San Joaquín',
  'San Miguel',
  'San Ramón',
  'Vitacura',
  'Puente Alto',
  'Pirque',
  'San José de Maipo',
  'Colina',
  'Lampa',
  'Tiltil',
  'San Bernardo',
  'Buin',
  'Calera de Tango',
  'Paine',
  'Melipilla',
  'Alhué',
  'Curacaví',
  'María Pinto',
  'San Pedro',
  'Talagante',
  'El Monte',
  'Isla de Maipo',
  'Padre Hurtado',
  'Peñaflor',
  // O'Higgins
  'Rancagua',
  'Codegua',
  'Coinco',
  'Coltauco',
  'Doñihue',
  'Graneros',
  'Las Cabras',
  'Machalí',
  'Malloa',
  'Mostazal',
  'Olivar',
  'Peumo',
  'Pichidegua',
  'Quinta de Tilcoco',
  'Rengo',
  'Requínoa',
  'San Vicente',
  'Pichilemu',
  'La Estrella',
  'Litueche',
  'Marchihue',
  'Navidad',
  'Paredones',
  'San Fernando',
  'Chépica',
  'Chimbarongo',
  'Lolol',
  'Nancagua',
  'Palmilla',
  'Peralillo',
  'Placilla',
  'Pumanque',
  'Santa Cruz',
  // Maule
  'Talca',
  'Constitución',
  'Curepto',
  'Empedrado',
  'Maule',
  'Pelarco',
  'Pencahue',
  'Río Claro',
  'San Clemente',
  'San Rafael',
  'Cauquenes',
  'Chanco',
  'Pelluhue',
  'Curicó',
  'Hualañé',
  'Licantén',
  'Molina',
  'Rauco',
  'Romeral',
  'Sagrada Familia',
  'Teno',
  'Vichuquén',
  'Linares',
  'Colbún',
  'Longaví',
  'Parral',
  'Retiro',
  'San Javier',
  'Villa Alegre',
  'Yerbas Buenas',
  // Ñuble
  'Chillán',
  'Bulnes',
  'Cobquecura',
  'Coelemu',
  'Coihueco',
  'El Carmen',
  'Ninhue',
  'Ñiquén',
  'Pemuco',
  'Pinto',
  'Portezuelo',
  'Quillón',
  'Quirihue',
  'Ránquil',
  'San Carlos',
  'San Fabián',
  'San Ignacio',
  'San Nicolás',
  'Treguaco',
  'Yungay',
  // Biobío
  'Concepción',
  'Coronel',
  'Chiguayante',
  'Florida',
  'Hualqui',
  'Lota',
  'Penco',
  'San Pedro de la Paz',
  'Santa Juana',
  'Talcahuano',
  'Tomé',
  'Hualpén',
  'Lebu',
  'Arauco',
  'Cañete',
  'Contulmo',
  'Curanilahue',
  'Los Álamos',
  'Tirúa',
  'Los Ángeles',
  'Antuco',
  'Cabrero',
  'Laja',
  'Mulchén',
  'Nacimiento',
  'Negrete',
  'Quilaco',
  'Quilleco',
  'San Rosendo',
  'Santa Bárbara',
  'Tucapel',
  'Yumbel',
  'Alto Biobío',
  // Araucanía
  'Temuco',
  'Carahue',
  'Cunco',
  'Curarrehue',
  'Freire',
  'Galvarino',
  'Gorbea',
  'Lautaro',
  'Loncoche',
  'Melipeuco',
  'Nueva Imperial',
  'Padre Las Casas',
  'Perquenco',
  'Pitrufquén',
  'Pucón',
  'Saavedra',
  'Teodoro Schmidt',
  'Toltén',
  'Vilcún',
  'Villarrica',
  'Cholchol',
  'Angol',
  'Collipulli',
  'Ercilla',
  'Lonquimay',
  'Los Sauces',
  'Lumaco',
  'Purén',
  'Renaico',
  'Traiguén',
  'Victoria',
  // Los Ríos
  'Valdivia',
  'Corral',
  'Lanco',
  'Los Lagos',
  'Máfil',
  'Mariquina',
  'Paillaco',
  'Panguipulli',
  'La Unión',
  'Futrono',
  'Lago Ranco',
  'Río Bueno',
  // Los Lagos
  'Puerto Montt',
  'Calbuco',
  'Cochamó',
  'Fresia',
  'Frutillar',
  'Los Muermos',
  'Llanquihue',
  'Maullín',
  'Puerto Varas',
  'Castro',
  'Chonchi',
  'Curaco de Vélez',
  'Dalcahue',
  'Puqueldón',
  'Queilén',
  'Quellón',
  'Quemchi',
  'Quinchao',
  'Osorno',
  'Puerto Octay',
  'Purranque',
  'Puyehue',
  'Río Negro',
  'San Juan de la Costa',
  'San Pablo',
  // Aysén
  'Coyhaique',
  'Lago Verde',
  'Aysén',
  'Cisnes',
  'Guaitecas',
  'Río Ibáñez',
  'Chile Chico',
  'Cochrane',
  "O'Higgins",
  'Tortel',
  // Magallanes
  'Punta Arenas',
  'Laguna Blanca',
  'Río Verde',
  'San Gregorio',
  'Cabo de Hornos',
  'Antártica',
  'Porvenir',
  'Primavera',
  'Timaukel',
  'Natales',
  'Torres del Paine',
];

// Flat enum with all comunas (keys normalized to ASCII-uppercase identifiers)
export enum ComunaEnum {
  ARICA = 'Arica',
  CAMARONES = 'Camarones',
  PUTRE = 'Putre',
  GENERAL_LAGOS = 'General Lagos',
  IQUIQUE = 'Iquique',
  ALTO_HOSPICIO = 'Alto Hospicio',
  POZO_ALMONTE = 'Pozo Almonte',
  CAMINA = 'Camiña',
  COLCHANE = 'Colchane',
  HUARA = 'Huara',
  PICA = 'Pica',
  ANTOFAGASTA = 'Antofagasta',
  MEJILLONES = 'Mejillones',
  SIERRA_GORDA = 'Sierra Gorda',
  TALTAL = 'Taltal',
  CALAMA = 'Calama',
  OLLAGUE = 'Ollagüe',
  SAN_PEDRO_DE_ATACAMA = 'San Pedro de Atacama',
  TOCOPILLA = 'Tocopilla',
  MARIA_ELENA = 'María Elena',
  COPIAPO = 'Copiapó',
  CALDERA = 'Caldera',
  TIERRA_AMARILLA = 'Tierra Amarilla',
  CHANARAL = 'Chañaral',
  DIEGO_DE_ALMAGRO = 'Diego de Almagro',
  VALLENAR = 'Vallenar',
  HUASCO = 'Huasco',
  FREIRINA = 'Freirina',
  ALTO_DEL_CARMEN = 'Alto del Carmen',
  LA_SERENA = 'La Serena',
  COQUIMBO = 'Coquimbo',
  ANDACOLLO = 'Andacollo',
  LA_HIGUERA = 'La Higuera',
  PAIGUANO = 'Paiguano',
  VICUNA = 'Vicuña',
  ILLAPEL = 'Illapel',
  CANELA = 'Canela',
  LOS_VILOS = 'Los Vilos',
  SALAMANCA = 'Salamanca',
  OVALLE = 'Ovalle',
  COMBARBALA = 'Combarbalá',
  MONTE_PATRIA = 'Monte Patria',
  PUNITAQUI = 'Punitaqui',
  RIO_HURTADO = 'Río Hurtado',
  VALPARAISO = 'Valparaíso',
  CASABLANCA = 'Casablanca',
  CONCON = 'Concón',
  JUAN_FERNANDEZ = 'Juan Fernández',
  PUCHUNCAVI = 'Puchuncaví',
  QUINTERO = 'Quintero',
  VINA_DEL_MAR = 'Viña del Mar',
  QUILPUE = 'Quilpué',
  LIMACHE = 'Limache',
  OLMUE = 'Olmué',
  VILLA_ALEMANA = 'Villa Alemana',
  ISLA_DE_PASCUA = 'Isla de Pascua',
  LOS_ANDES = 'Los Andes',
  CALLE_LARGA = 'Calle Larga',
  RINCONADA = 'Rinconada',
  SAN_ESTEBAN = 'San Esteban',
  LA_LIGUA = 'La Ligua',
  CABILDO = 'Cabildo',
  PAPUDO = 'Papudo',
  PETORCA = 'Petorca',
  ZAPALLAR = 'Zapallar',
  QUILLOTA = 'Quillota',
  LA_CALERA = 'La Calera',
  LA_CRUZ = 'La Cruz',
  NOGALES = 'Nogales',
  SAN_ANTONIO = 'San Antonio',
  ALGARROBO = 'Algarrobo',
  CARTAGENA = 'Cartagena',
  EL_QUISCO = 'El Quisco',
  EL_TABO = 'El Tabo',
  SANTO_DOMINGO = 'Santo Domingo',
  SAN_FELIPE = 'San Felipe',
  CATEMU = 'Catemu',
  LLAILLAY = 'Llaillay',
  PANQUEHUE = 'Panquehue',
  PUTAENDO = 'Putaendo',
  SANTA_MARIA = 'Santa María',
  CERRILLOS = 'Cerrillos',
  CERRO_NAVIA = 'Cerro Navia',
  CONCHALI = 'Conchalí',
  EL_BOSQUE = 'El Bosque',
  ESTACION_CENTRAL = 'Estación Central',
  HUECHURABA = 'Huechuraba',
  INDEPENDENCIA = 'Independencia',
  LA_CISTERNA = 'La Cisterna',
  LA_FLORIDA = 'La Florida',
  LA_GRANJA = 'La Granja',
  LA_PINTANA = 'La Pintana',
  LA_REINA = 'La Reina',
  LAS_CONDES = 'Las Condes',
  LO_BARNECHEA = 'Lo Barnechea',
  LO_ESPEJO = 'Lo Espejo',
  LO_PRADO = 'Lo Prado',
  MACUL = 'Macul',
  MAIPU = 'Maipú',
  NUNOA = 'Ñuñoa',
  PEDRO_AGUIRRE_CERDA = 'Pedro Aguirre Cerda',
  PENALOLEN = 'Peñalolén',
  PROVIDENCIA = 'Providencia',
  PUDAHUEL = 'Pudahuel',
  QUILICURA = 'Quilicura',
  QUINTA_NORMAL = 'Quinta Normal',
  RECOLETA = 'Recoleta',
  RENCA = 'Renca',
  SAN_JOAQUIN = 'San Joaquín',
  SAN_MIGUEL = 'San Miguel',
  SAN_RAMON = 'San Ramón',
  VITACURA = 'Vitacura',
  PUENTE_ALTO = 'Puente Alto',
  PIRQUE = 'Pirque',
  SAN_JOSE_DE_MAIPO = 'San José de Maipo',
  COLINA = 'Colina',
  LAMPA = 'Lampa',
  TIL_TIL = 'Tiltil',
  SAN_BERNARDO = 'San Bernardo',
  BUIN = 'Buin',
  CALERA_DE_TANGO = 'Calera de Tango',
  PAINE = 'Paine',
  MELIPILLA = 'Melipilla',
  ALHUE = 'Alhué',
  CURACAVI = 'Curacaví',
  MARIA_PINTO = 'María Pinto',
  SAN_PEDRO = 'San Pedro',
  TALAGANTE = 'Talagante',
  EL_MONTE = 'El Monte',
  ISLA_DE_MAIPO = 'Isla de Maipo',
  PADRE_HURTADO = 'Padre Hurtado',
  PENAFLOR = 'Peñaflor',
  RANCAGUA = 'Rancagua',
  CODEGUA = 'Codegua',
  COINCO = 'Coinco',
  COLTAUCO = 'Coltauco',
  DONIHUE = 'Doñihue',
  GRANEROS = 'Graneros',
  LAS_CABRAS = 'Las Cabras',
  MACHALI = 'Machalí',
  MALLOA = 'Malloa',
  MOSTAZAL = 'Mostazal',
  OLIVAR = 'Olivar',
  PEUMO = 'Peumo',
  PICHIDEGUA = 'Pichidegua',
  QUINTA_DE_TILCOCO = 'Quinta de Tilcoco',
  RENGO = 'Rengo',
  REQUINOA = 'Requínoa',
  SAN_VICENTE = 'San Vicente',
  PICHILEMU = 'Pichilemu',
  LA_ESTRELLA = 'La Estrella',
  LITUECHE = 'Litueche',
  MARCHIHUE = 'Marchihue',
  NAVIDAD = 'Navidad',
  PAREDONES = 'Paredones',
  SAN_FERNANDO = 'San Fernando',
  CHEPICA = 'Chépica',
  CHIMBARONGO = 'Chimbarongo',
  LOLOL = 'Lolol',
  NANCAGUA = 'Nancagua',
  PAMILLA = 'Palmilla',
  PERALILLO = 'Peralillo',
  PLACILLA = 'Placilla',
  PUMANQUE = 'Pumanque',
  SANTA_CRUZ = 'Santa Cruz',
  TALCA = 'Talca',
  CONSTITUCION = 'Constitución',
  CUREPTO = 'Curepto',
  EMPEDRADO = 'Empedrado',
  MAULE = 'Maule',
  PELARCO = 'Pelarco',
  PENCAHUE = 'Pencahue',
  RIO_CLARO = 'Río Claro',
  SAN_CLEMENTE = 'San Clemente',
  SAN_RAFAEL = 'San Rafael',
  CAUQUENES = 'Cauquenes',
  CHANCO = 'Chanco',
  PELLUHUE = 'Pelluhue',
  CURICO = 'Curicó',
  HUALANE = 'Hualañé',
  LICANTEN = 'Licantén',
  MOLINA = 'Molina',
  RAUCO = 'Rauco',
  ROMERAL = 'Romeral',
  SAGRADA_FAMILIA = 'Sagrada Familia',
  TENO = 'Teno',
  VICHUQUEN = 'Vichuquén',
  LINARES = 'Linares',
  COLBUN = 'Colbún',
  LONGAVI = 'Longaví',
  PARRAL = 'Parral',
  RETIRO = 'Retiro',
  SAN_JAVIER = 'San Javier',
  VILLA_ALEGRE = 'Villa Alegre',
  YERBAS_BUENAS = 'Yerbas Buenas',
  CHILLAN = 'Chillán',
  BULNES = 'Bulnes',
  COBQUECURA = 'Cobquecura',
  COELEMU = 'Coelemu',
  COIHUECO = 'Coihueco',
  EL_CARMEN = 'El Carmen',
  NINHUE = 'Ninhue',
  NIQUEN = 'Ñiquén',
  PEMUCO = 'Pemuco',
  PINTO = 'Pinto',
  PORTEZUELO = 'Portezuelo',
  QUILLON = 'Quillón',
  QUIRIHUE = 'Quirihue',
  RANQUIL = 'Ránquil',
  SAN_CARLOS = 'San Carlos',
  SAN_FABIAN = 'San Fabián',
  SAN_IGNACIO = 'San Ignacio',
  SAN_NICOLAS = 'San Nicolás',
  TREGUACO = 'Treguaco',
  YUNGAY = 'Yungay',
  CONCEPCION = 'Concepción',
  CORONEL = 'Coronel',
  CHIGUAYANTE = 'Chiguayante',
  FLORIDA = 'Florida',
  HUALQUI = 'Hualqui',
  LOTA = 'Lota',
  PENCO = 'Penco',
  SAN_PEDRO_DE_LA_PAZ = 'San Pedro de la Paz',
  SANTA_JUANA = 'Santa Juana',
  TALCAHUANO = 'Talcahuano',
  TOME = 'Tomé',
  HUALPEN = 'Hualpén',
  LEBU = 'Lebu',
  ARAUCO = 'Arauco',
  CANETE = 'Cañete',
  CONTULMO = 'Contulmo',
  CURANILAHUE = 'Curanilahue',
  LOS_ALAMOS = 'Los Álamos',
  TIRUA = 'Tirúa',
  LOS_ANGELES = 'Los Ángeles',
  ANTUCO = 'Antuco',
  CABRERO = 'Cabrero',
  LAJA = 'Laja',
  MULCHEN = 'Mulchén',
  NACIMIENTO = 'Nacimiento',
  NEGRETE = 'Negrete',
  QUILACO = 'Quilaco',
  QUILLECO = 'Quilleco',
  SAN_ROSENDO = 'San Rosendo',
  SANTA_BARBARA = 'Santa Bárbara',
  TUCAPEL = 'Tucapel',
  YUMBEL = 'Yumbel',
  ALTO_BIOBIO = 'Alto Biobío',
  TEMUCO = 'Temuco',
  CARAHUE = 'Carahue',
  CUNCO = 'Cunco',
  CURARREHUE = 'Curarrehue',
  FREIRE = 'Freire',
  GALVARINO = 'Galvarino',
  GORBEA = 'Gorbea',
  LAUTARO = 'Lautaro',
  LONCOCHE = 'Loncoche',
  MELIPEUCO = 'Melipeuco',
  NUEVA_IMPERIAL = 'Nueva Imperial',
  PADRE_LAS_CASAS = 'Padre Las Casas',
  PERQUENCO = 'Perquenco',
  PITRUFQUEN = 'Pitrufquén',
  PUCON = 'Pucón',
  SAAVEDRA = 'Saavedra',
  TEODORO_SCHMIDT = 'Teodoro Schmidt',
  TOLTEN = 'Toltén',
  VILCUN = 'Vilcún',
  VILLARRICA = 'Villarrica',
  CHOLCHOL = 'Cholchol',
  ANGOL = 'Angol',
  COLLIPULLI = 'Collipulli',
  ERCILLA = 'Ercilla',
  LONQUIMAY = 'Lonquimay',
  LOS_SAUCES = 'Los Sauces',
  LUMACO = 'Lumaco',
  PUREN = 'Purén',
  RENAICO = 'Renaico',
  TRAIGUEN = 'Traiguén',
  VICTORIA = 'Victoria',
  VALDIVIA = 'Valdivia',
  CORRAL = 'Corral',
  LANCO = 'Lanco',
  LOS_LAGOS = 'Los Lagos',
  MAFIL = 'Máfil',
  MARIQUINA = 'Mariquina',
  PAILLACO = 'Paillaco',
  PANGUIPULLI = 'Panguipulli',
  LA_UNION = 'La Unión',
  FUTRONO = 'Futrono',
  LAGO_RANCO = 'Lago Ranco',
  RIO_BUENO = 'Río Bueno',
  PUERTO_MONTT = 'Puerto Montt',
  CALBUCO = 'Calbuco',
  COCHAMO = 'Cochamó',
  FRESIA = 'Fresia',
  FRUTILLAR = 'Frutillar',
  LOS_MUERMOS = 'Los Muermos',
  LLANQUIHUE = 'Llanquihue',
  MAULLIN = 'Maullín',
  PUERTO_VARAS = 'Puerto Varas',
  CASTRO = 'Castro',
  CHONCHI = 'Chonchi',
  CURACO_DE_VELEZ = 'Curaco de Vélez',
  DALCAHUE = 'Dalcahue',
  PUQUELDON = 'Puqueldón',
  QUEILEN = 'Queilén',
  QUELLON = 'Quellón',
  QUEMCHI = 'Quemchi',
  QUINCHAO = 'Quinchao',
  OSORNO = 'Osorno',
  PUERTO_OCTAY = 'Puerto Octay',
  PURRANQUE = 'Purranque',
  PUYEHUE = 'Puyehue',
  RIO_NEGRO = 'Río Negro',
  SAN_JUAN_DE_LA_COSTA = 'San Juan de la Costa',
  SAN_PABLO = 'San Pablo',
  COYHAIQUE = 'Coyhaique',
  LAGO_VERDE = 'Lago Verde',
  AYSEN = 'Aysén',
  CISNES = 'Cisnes',
  GUAITECAS = 'Guaitecas',
  RIO_IBANEZ = 'Río Ibáñez',
  CHILE_CHICO = 'Chile Chico',
  COCHRANE = 'Cochrane',
  OHIGGINS = "O'Higgins",
  TORTEL = 'Tortel',
  PUNTA_ARENAS = 'Punta Arenas',
  LAGUNA_BLANCA = 'Laguna Blanca',
  RIO_VERDE = 'Río Verde',
  SAN_GREGORIO = 'San Gregorio',
  CABO_DE_HORNOS = 'Cabo de Hornos',
  ANTARTICA = 'Antártica',
  PORVENIR = 'Porvenir',
  PRIMAVERA = 'Primavera',
  TIMAUKEL = 'Timaukel',
  NATALES = 'Natales',
  TORRES_DEL_PAINE = 'Torres del Paine',
}
