// Enums copiados desde el backend para usar en el frontend

export enum RegionEnum {
  ARICA_Y_PARINACOTA = 'Arica y Parinacota',
  TARAPACA = 'Tarapacá',
  ANTOFAGASTA = 'Antofagasta',
  ATACAMA = 'Atacama',
  COQUIMBO = 'Coquimbo',
  VALPARAISO = 'Valparaíso',
  METROPOLITANA = 'Metropolitana de Santiago',
  OHIGGINS = "O'Higgins",
  MAULE = 'Maule',
  ÑUBLE = 'Ñuble',
  BIOBIO = 'Biobío',
  ARAUCANIA = 'La Araucanía',
  LOS_RIOS = 'Los Ríos',
  LOS_LAGOS = 'Los Lagos',
  AYSEN = 'Aysén',
  MAGALLANES = 'Magallanes',
}

export enum ComunaEnum {
  ARICA = 'Arica',
  CAMARONES = 'Camarones',
  PUTRE = 'Putre',
  GENERAL_LAGOS = 'General Lagos',
  IQUIQUE = 'Iquique',
  ALTO_HOSPICIO = 'Alto Hospicio',
  POZO_ALMONTE = 'Pozo Almonte',
  CAMINA = 'Camiña',
  COLCHANE = 'Colchane',
  HUARA = 'Huara',
  PICA = 'Pica',
  ANTOFAGASTA = 'Antofagasta',
  MEJILLONES = 'Mejillones',
  SIERRA_GORDA = 'Sierra Gorda',
  TALTAL = 'Taltal',
  CALAMA = 'Calama',
  OLLAGUE = 'Ollagüe',
  SAN_PEDRO_DE_ATACAMA = 'San Pedro de Atacama',
  TOCOPILLA = 'Tocopilla',
  MARIA_ELENA = 'María Elena',
  COPIAPO = 'Copiapó',
  CALDERA = 'Caldera',
  TIERRA_AMARILLA = 'Tierra Amarilla',
  CHANARAL = 'Chañaral',
  DIEGO_DE_ALMAGRO = 'Diego de Almagro',
  VALLENAR = 'Vallenar',
  HUASCO = 'Huasco',
  FREIRINA = 'Freirina',
  ALTO_DEL_CARMEN = 'Alto del Carmen',
  LA_SERENA = 'La Serena',
  COQUIMBO = 'Coquimbo',
  ANDACOLLO = 'Andacollo',
  LA_HIGUERA = 'La Higuera',
  PAIGUANO = 'Paiguano',
  VICUNA = 'Vicuña',
  ILLAPEL = 'Illapel',
  CANELA = 'Canela',
  LOS_VILOS = 'Los Vilos',
  SALAMANCA = 'Salamanca',
  OVALLE = 'Ovalle',
  COMBARBALA = 'Combarbalá',
  MONTE_PATRIA = 'Monte Patria',
  PUNITAQUI = 'Punitaqui',
  RIO_HURTADO = 'Río Hurtado',
  VALPARAISO = 'Valparaíso',
  CASABLANCA = 'Casablanca',
  CONCON = 'Concón',
  JUAN_FERNANDEZ = 'Juan Fernández',
  PUCHUNCAVI = 'Puchuncaví',
  QUINTERO = 'Quintero',
  VINA_DEL_MAR = 'Viña del Mar',
  QUILPUE = 'Quilpué',
  LIMACHE = 'Limache',
  OLMUE = 'Olmué',
  VILLA_ALEMANA = 'Villa Alemana',
  ISLA_DE_PASCUA = 'Isla de Pascua',
  LOS_ANDES = 'Los Andes',
  CALLE_LARGA = 'Calle Larga',
  RINCONADA = 'Rinconada',
  SAN_ESTEBAN = 'San Esteban',
  LA_LIGUA = 'La Ligua',
  CABILDO = 'Cabildo',
  PAPUDO = 'Papudo',
  PETORCA = 'Petorca',
  ZAPALLAR = 'Zapallar',
  QUILLOTA = 'Quillota',
  LA_CALERA = 'La Calera',
  LA_CRUZ = 'La Cruz',
  NOGALES = 'Nogales',
  SAN_ANTONIO = 'San Antonio',
  ALGARROBO = 'Algarrobo',
  CARTAGENA = 'Cartagena',
  EL_QUISCO = 'El Quisco',
  EL_TABO = 'El Tabo',
  SANTO_DOMINGO = 'Santo Domingo',
  SAN_FELIPE = 'San Felipe',
  CATEMU = 'Catemu',
  LLAILLAY = 'Llaillay',
  PANQUEHUE = 'Panquehue',
  PUTAENDO = 'Putaendo',
  SANTA_MARIA = 'Santa María',
  CERRILLOS = 'Cerrillos',
  CERRO_NAVIA = 'Cerro Navia',
  CONCHALI = 'Conchalí',
  EL_BOSQUE = 'El Bosque',
  ESTACION_CENTRAL = 'Estación Central',
  HUECHURABA = 'Huechuraba',
  INDEPENDENCIA = 'Independencia',
  LA_CISTERNA = 'La Cisterna',
  LA_FLORIDA = 'La Florida',
  LA_GRANJA = 'La Granja',
  LA_PINTANA = 'La Pintana',
  LA_REINA = 'La Reina',
  LAS_CONDES = 'Las Condes',
  LO_BARNECHEA = 'Lo Barnechea',
  LO_ESPEJO = 'Lo Espejo',
  LO_PRADO = 'Lo Prado',
  MACUL = 'Macul',
  MAIPU = 'Maipú',
  NUNOA = 'Ñuñoa',
  PEDRO_AGUIRRE_CERDA = 'Pedro Aguirre Cerda',
  PENALOLEN = 'Peñalolén',
  PROVIDENCIA = 'Providencia',
  PUDAHUEL = 'Pudahuel',
  QUILICURA = 'Quilicura',
  QUINTA_NORMAL = 'Quinta Normal',
  RECOLETA = 'Recoleta',
  RENCA = 'Renca',
  SAN_JOAQUIN = 'San Joaquín',
  SAN_MIGUEL = 'San Miguel',
  SAN_RAMON = 'San Ramón',
  VITACURA = 'Vitacura',
  PUENTE_ALTO = 'Puente Alto',
  PIRQUE = 'Pirque',
  SAN_JOSE_DE_MAIPO = 'San José de Maipo',
  COLINA = 'Colina',
  LAMPA = 'Lampa',
  TIL_TIL = 'Tiltil',
  SAN_BERNARDO = 'San Bernardo',
  BUIN = 'Buin',
  CALERA_DE_TANGO = 'Calera de Tango',
  PAINE = 'Paine',
  MELIPILLA = 'Melipilla',
  ALHUE = 'Alhué',
  CURACAVI = 'Curacaví',
  MARIA_PINTO = 'María Pinto',
  SAN_PEDRO = 'San Pedro',
  TALAGANTE = 'Talagante',
  EL_MONTE = 'El Monte',
  ISLA_DE_MAIPO = 'Isla de Maipo',
  PADRE_HURTADO = 'Padre Hurtado',
  PENAFLOR = 'Peñaflor',
  RANCAGUA = 'Rancagua',
  CODEGUA = 'Codegua',
  COINCO = 'Coinco',
  COLTAUCO = 'Coltauco',
  DONIHUE = 'Doñihue',
  GRANEROS = 'Graneros',
  LAS_CABRAS = 'Las Cabras',
  MACHALI = 'Machalí',
  MALLOA = 'Malloa',
  MOSTAZAL = 'Mostazal',
  OLIVAR = 'Olivar',
  PEUMO = 'Peumo',
  PICHIDEGUA = 'Pichidegua',
  QUINTA_DE_TILCOCO = 'Quinta de Tilcoco',
  RENGO = 'Rengo',
  REQUINOA = 'Requínoa',
  SAN_VICENTE = 'San Vicente',
  PICHILEMU = 'Pichilemu',
  LA_ESTRELLA = 'La Estrella',
  LITUECHE = 'Litueche',
  MARCHIHUE = 'Marchihue',
  NAVIDAD = 'Navidad',
  PAREDONES = 'Paredones',
  SAN_FERNANDO = 'San Fernando',
  CHEPICA = 'Chépica',
  CHIMBARONGO = 'Chimbarongo',
  LOLOL = 'Lolol',
  NANCAGUA = 'Nancagua',
  PAMILLA = 'Palmilla',
  PERALILLO = 'Peralillo',
  PLACILLA = 'Placilla',
  PUMANQUE = 'Pumanque',
  SANTA_CRUZ = 'Santa Cruz',
  TALCA = 'Talca',
  CONSTITUCION = 'Constitución',
  CUREPTO = 'Curepto',
  EMPEDRADO = 'Empedrado',
  MAULE = 'Maule',
  PELARCO = 'Pelarco',
  PENCAHUE = 'Pencahue',
  RIO_CLARO = 'Río Claro',
  SAN_CLEMENTE = 'San Clemente',
  SAN_RAFAEL = 'San Rafael',
  CAUQUENES = 'Cauquenes',
  CHANCO = 'Chanco',
  PELLUHUE = 'Pelluhue',
  CURICO = 'Curicó',
  HUALANE = 'Hualañé',
  LICANTEN = 'Licantén',
  MOLINA = 'Molina',
  RAUCO = 'Rauco',
  ROMERAL = 'Romeral',
  SAGRADA_FAMILIA = 'Sagrada Familia',
  TENO = 'Teno',
  VICHUQUEN = 'Vichuquén',
  LINARES = 'Linares',
  COLBUN = 'Colbún',
  LONGAVI = 'Longaví',
  PARRAL = 'Parral',
  RETIRO = 'Retiro',
  SAN_JAVIER = 'San Javier',
  VILLA_ALEGRE = 'Villa Alegre',
  YERBAS_BUENAS = 'Yerbas Buenas',
  CHILLAN = 'Chillán',
  BULNES = 'Bulnes',
  COBQUECURA = 'Cobquecura',
  COELEMU = 'Coelemu',
  COIHUECO = 'Coihueco',
  EL_CARMEN = 'El Carmen',
  NINHUE = 'Ninhue',
  NIQUEN = 'Ñiquén',
  PEMUCO = 'Pemuco',
  PINTO = 'Pinto',
  PORTEZUELO = 'Portezuelo',
  QUILLON = 'Quillón',
  QUIRIHUE = 'Quirihue',
  RANQUIL = 'Ránquil',
  SAN_CARLOS = 'San Carlos',
  SAN_FABIAN = 'San Fabián',
  SAN_IGNACIO = 'San Ignacio',
  SAN_NICOLAS = 'San Nicolás',
  TREGUACO = 'Treguaco',
  YUNGAY = 'Yungay',
  CONCEPCION = 'Concepción',
  CORONEL = 'Coronel',
  CHIGUAYANTE = 'Chiguayante',
  FLORIDA = 'Florida',
  HUALQUI = 'Hualqui',
  LOTA = 'Lota',
  PENCO = 'Penco',
  SAN_PEDRO_DE_LA_PAZ = 'San Pedro de la Paz',
  SANTA_JUANA = 'Santa Juana',
  TALCAHUANO = 'Talcahuano',
  TOME = 'Tomé',
  HUALPEN = 'Hualpén',
  LEBU = 'Lebu',
  ARAUCO = 'Arauco',
  CANETE = 'Cañete',
  CONTULMO = 'Contulmo',
  CURANILAHUE = 'Curanilahue',
  LOS_ALAMOS = 'Los Álamos',
  TIRUA = 'Tirúa',
  LOS_ANGELES = 'Los Ángeles',
  ANTUCO = 'Antuco',
  CABRERO = 'Cabrero',
  LAJA = 'Laja',
  MULCHEN = 'Mulchén',
}

// PropertyStatus enum copiado desde el backend para usar en el frontend

export enum PropertyStatus {
  REQUEST = 'REQUEST',
  PRE_APPROVED = 'PRE-APPROVED',
  PUBLISHED = 'PUBLISHED',
  INACTIVE = 'INACTIVE',
  SOLD = 'SOLD',
  RENTED = 'RENTED',
  CONTRACT_IN_PROGRESS = 'CONTRACT-IN-PROGRESS',
}

// Mapeos para transformar valores del frontend (strings) a backend (números)
export const PROPERTY_STATUS_MAPPING: Record<string, number> = {
  'REQUEST': 1,
  'PRE-APPROVED': 2,
  'PUBLISHED': 3,
  'INACTIVE': 4,
  'SOLD': 5,
  'RENTED': 6,
  'CONTRACT-IN-PROGRESS': 7, // Nota: El DTO solo tiene hasta 6, pero mantengo consistencia
};

export const PROPERTY_OPERATION_TYPE_MAPPING: Record<string, number> = {
  'SALE': 1,
  'RENT': 2,
};

export const CURRENCY_PRICE_MAPPING: Record<string, number> = {
  'CLP': 1,
  'UF': 2,
};