'use server';

import { env } from '@/lib/env';

// In a real-world scenario, this would come from a database.
const regions = [
  { id: '1', name: 'Arica y Parinacota' },
  { id: '2', name: 'Tarapacá' },
  { id: '3', name: 'Antofagasta' },
  { id: '4', name: 'Atacama' },
  { id: '5', name: 'Coquimbo' },
  { id: '6', name: 'Valparaíso' },
  { id: '7', name: 'Metropolitana de Santiago' },
  { id: '8', name: "O'Higgins" },
  { id: '9', name: 'Maule' },
  { id: '10', name: 'Ñuble' },
  { id: '11', name: 'Biobío' },
  { id: '12', name: 'La Araucanía' },
  { id: '13', name: 'Los Ríos' },
  { id: '14', name: 'Los Lagos' },
  { id: '15', name: 'Aysén' },
  { id: '16', name: 'Magallanes' },
];

const communesByRegion: { [key: string]: { id: string, name: string }[] } = {
    '1': [ // Arica y Parinacota
        { id: '101', name: 'Arica' },
        { id: '102', name: 'Camarones' },
        { id: '103', name: 'Putre' },
        { id: '104', name: 'General Lagos' },
    ],
    '2': [ // Tarapacá
        { id: '201', name: 'Iquique' },
        { id: '202', name: 'Alto Hospicio' },
        { id: '203', name: 'Pozo Almonte' },
        { id: '204', name: 'Camiña' },
        { id: '205', name: 'Colchane' },
        { id: '206', name: 'Huara' },
        { id: '207', name: 'Pica' },
    ],
    '3': [ // Antofagasta
        { id: '301', name: 'Antofagasta' },
        { id: '302', name: 'Calama' },
        { id: '303', name: 'Tocopilla' },
        { id: '304', name: 'Mejillones' },
        { id: '305', name: 'Taltal' },
        { id: '306', name: 'Sierra Gorda' },
        { id: '307', name: 'Ollagüe' },
        { id: '308', name: 'San Pedro de Atacama' },
        { id: '309', name: 'María Elena' },
    ],
    '4': [ // Atacama
        { id: '401', name: 'Copiapó' },
        { id: '402', name: 'Caldera' },
        { id: '403', name: 'Vallenar' },
        { id: '404', name: 'Chañaral' },
        { id: '405', name: 'Diego de Almagro' },
        { id: '406', name: 'El Salvador' },
        { id: '407', name: 'Huasco' },
        { id: '408', name: 'Tierra Amarilla' },
        { id: '409', name: 'Alto del Carmen' },
        { id: '410', name: 'Freirina' },
    ],
    '5': [ // Coquimbo
        { id: '501', name: 'La Serena' },
        { id: '502', name: 'Coquimbo' },
        { id: '503', name: 'Ovalle' },
        { id: '504', name: 'Illapel' },
        { id: '505', name: 'Salamanca' },
        { id: '506', name: 'Los Vilos' },
        { id: '507', name: 'Monte Patria' },
        { id: '508', name: 'Punitaqui' },
        { id: '509', name: 'Vicuña' },
        { id: '510', name: 'Paihuano' },
        { id: '511', name: 'Andacollo' },
        { id: '512', name: 'Rio Hurtado' },
        { id: '513', name: 'Combarbalá' },
        { id: '514', name: 'Canela' },
        { id: '515', name: 'Mincha' },
    ],
    '6': [ // Valparaíso
        { id: '601', name: 'Valparaíso' },
        { id: '602', name: 'Viña del Mar' },
        { id: '603', name: 'Concón' },
        { id: '604', name: 'Quilpué' },
        { id: '605', name: 'Villa Alemana' },
        { id: '606', name: 'Quillota' },
        { id: '607', name: 'La Calera' },
        { id: '608', name: 'Hijuelas' },
        { id: '609', name: 'La Ligua' },
        { id: '610', name: 'Cabildo' },
        { id: '611', name: 'Papudo' },
        { id: '612', name: 'Petorca' },
        { id: '613', name: 'Zapallar' },
        { id: '614', name: 'Puchuncaví' },
        { id: '615', name: 'Quintero' },
        { id: '616', name: 'Rinconada' },
        { id: '617', name: 'Los Andes' },
        { id: '618', name: 'Calle Larga' },
        { id: '619', name: 'Rengo' },
        { id: '620', name: 'San Felipe' },
        { id: '621', name: 'Llaillay' },
        { id: '622', name: 'Putaendo' },
        { id: '623', name: 'Santa María' },
        { id: '624', name: 'Catemu' },
        { id: '625', name: 'Panquehue' },
        { id: '626', name: 'San Antonio' },
        { id: '627', name: 'Cartagena' },
        { id: '628', name: 'El Tabo' },
        { id: '629', name: 'El Quisco' },
        { id: '630', name: 'Algarrobo' },
        { id: '631', name: 'Santo Domingo' },
        { id: '632', name: 'Casablanca' },
        { id: '633', name: 'Juan Fernández' },
        { id: '634', name: 'Isla de Pascua' },
    ],
    '7': [ // Metropolitana
        { id: '701', name: 'Santiago' },
        { id: '702', name: 'Providencia' },
        { id: '703', name: 'Las Condes' },
        { id: '704', name: 'La Reina' },
        { id: '705', name: 'Ñuñoa' },
        { id: '706', name: 'Macul' },
        { id: '707', name: 'Peñalolén' },
        { id: '708', name: 'Recoleta' },
        { id: '709', name: 'San Bernardo' },
        { id: '710', name: 'Maipú' },
        { id: '711', name: 'Quinta Normal' },
        { id: '712', name: 'Estación Central' },
        { id: '713', name: 'Pudahuel' },
        { id: '714', name: 'Independencia' },
        { id: '715', name: 'Colina' },
        { id: '716', name: 'Lampa' },
        { id: '717', name: 'Paine' },
        { id: '718', name: 'Buin' },
        { id: '719', name: 'Vitacura' },
        { id: '720', name: 'Renca' },
        { id: '721', name: 'La Florida' },
        { id: '722', name: 'La Cisterna' },
        { id: '723', name: 'La Granja' },
        { id: '724', name: 'La Pintana' },
        { id: '725', name: 'La Chascona' },
        { id: '726', name: 'Lo Barnechea' },
        { id: '727', name: 'Lo Espejo' },
        { id: '728', name: 'Lo Prado' },
        { id: '729', name: 'Cerro Navia' },
        { id: '730', name: 'Conchalí' },
        { id: '731', name: 'El Bosque' },
        { id: '732', name: 'El Monte' },
        { id: '733', name: 'Huechuraba' },
        { id: '734', name: 'Isla de Maipo' },
        { id: '735', name: 'Padre Hurtado' },
        { id: '736', name: 'Pedro Aguirre Cerda' },
        { id: '737', name: 'Pirque' },
        { id: '738', name: 'Puente Alto' },
        { id: '739', name: 'San Joaquín' },
        { id: '740', name: 'San José de Maipo' },
        { id: '741', name: 'San Miguel' },
        { id: '742', name: 'San Ramón' },
        { id: '743', name: 'Talagante' },
        { id: '744', name: 'Tiltil' },
    ],
    '8': [ // O'Higgins
        { id: '801', name: 'Rancagua' },
        { id: '802', name: 'Rengo' },
        { id: '803', name: 'San Vicente' },
        { id: '804', name: 'Machalí' },
        { id: '805', name: 'Graneros' },
        { id: '806', name: 'Mostazal' },
        { id: '807', name: 'Codegua' },
        { id: '808', name: 'Coinco' },
        { id: '809', name: 'Coltauco' },
        { id: '810', name: 'Doñihue' },
        { id: '811', name: 'Las Cabras' },
        { id: '812', name: 'Malloa' },
        { id: '813', name: 'Olivar' },
        { id: '814', name: 'Peumo' },
        { id: '815', name: 'Pichidegua' },
        { id: '816', name: 'Quinta de Tilcoco' },
        { id: '817', name: 'Requínoa' },
        { id: '818', name: 'San Fernando' },
        { id: '819', name: 'Chimbarongo' },
        { id: '820', name: 'Lolol' },
        { id: '821', name: 'Nancagua' },
        { id: '822', name: 'Palmilla' },
        { id: '823', name: 'Peralillo' },
        { id: '824', name: 'Placilla' },
        { id: '825', name: 'Pumanque' },
        { id: '826', name: 'Santa Cruz' },
        { id: '827', name: 'Litueche' },
        { id: '828', name: 'Marchihue' },
        { id: '829', name: 'Navidad' },
        { id: '830', name: 'Paredones' },
        { id: '831', name: 'Pichilemu' },
        { id: '832', name: 'Chepica' },
        { id: '833', name: 'La Estrella' },
    ],
    '9': [ // Maule
        { id: '901', name: 'Talca' },
        { id: '902', name: 'Curicó' },
        { id: '903', name: 'Linares' },
        { id: '904', name: 'Constitución' },
        { id: '905', name: 'Cauquenes' },
        { id: '906', name: 'Parral' },
        { id: '907', name: 'San Clemente' },
        { id: '908', name: 'Pencahue' },
        { id: '909', name: 'Maule' },
        { id: '910', name: 'San Javier' },
        { id: '911', name: 'Villa Alegre' },
        { id: '912', name: 'Yerbas Buenas' },
        { id: '913', name: 'Colbún' },
        { id: '914', name: 'Longaví' },
        { id: '915', name: 'Retiro' },
        { id: '916', name: 'San Rafael' },
        { id: '917', name: 'Teno' },
        { id: '918', name: 'Romeral' },
        { id: '919', name: 'Rauco' },
        { id: '920', name: 'Licantén' },
        { id: '921', name: 'Vichuquén' },
        { id: '922', name: 'Molina' },
        { id: '923', name: 'Hualañé' },
        { id: '924', name: 'Curepto' },
        { id: '925', name: 'Pelarco' },
        { id: '926', name: 'Río Claro' },
        { id: '927', name: 'Sagrada Familia' },
        { id: '928', name: 'Chanco' },
        { id: '929', name: 'Empedrado' },
        { id: '930', name: 'Pelluhue' },
    ],
    '10': [ // Ñuble
        { id: '1001', name: 'Chillán' },
        { id: '1002', name: 'Chillán Viejo' },
        { id: '1003', name: 'Bulnes' },
        { id: '1004', name: 'Quillón' },
        { id: '1005', name: 'El Carmen' },
        { id: '1006', name: 'Pemuco' },
        { id: '1007', name: 'Yungay' },
        { id: '1008', name: 'Ránquil' },
        { id: '1009', name: 'Portezuelo' },
        { id: '1010', name: 'Coelemu' },
        { id: '1011', name: 'Treguaco' },
        { id: '1012', name: 'San Carlos' },
        { id: '1013', name: 'Coihueco' },
        { id: '1014', name: 'Ñiquén' },
        { id: '1015', name: 'San Fabián' },
        { id: '1016', name: 'San Nicolás' },
        { id: '1017', name: 'Cobquecura' },
        { id: '1018', name: 'Quirihue' },
        { id: '1019', name: 'Ninhue' },
        { id: '1020', name: 'Trehuaco' },
        { id: '1021', name: 'San Ignacio' },
    ],
    '11': [ // Biobío
        { id: '1101', name: 'Concepción' },
        { id: '1102', name: 'Talcahuano' },
        { id: '1103', name: 'Chiguayante' },
        { id: '1104', name: 'San Pedro de la Paz' },
        { id: '1105', name: 'Hualpén' },
        { id: '1106', name: 'Penco' },
        { id: '1107', name: 'Tomé' },
        { id: '1108', name: 'Coronel' },
        { id: '1109', name: 'Lota' },
        { id: '1110', name: 'Arauco' },
        { id: '1111', name: 'Cañete' },
        { id: '1112', name: 'Contulmo' },
        { id: '1113', name: 'Curanilahue' },
        { id: '1114', name: 'Lebu' },
        { id: '1115', name: 'Los Álamos' },
        { id: '1116', name: 'Tirúa' },
        { id: '1117', name: 'Los Ángeles' },
        { id: '1118', name: 'Antuco' },
        { id: '1119', name: 'Cabrero' },
        { id: '1120', name: 'Laja' },
        { id: '1121', name: 'Mulchén' },
        { id: '1122', name: 'Nacimiento' },
        { id: '1123', name: 'Negrete' },
        { id: '1124', name: 'Quilaco' },
        { id: '1125', name: 'Quilleco' },
        { id: '1126', name: 'San Rosendo' },
        { id: '1127', name: 'Santa Bárbara' },
        { id: '1128', name: 'Tucapel' },
        { id: '1129', name: 'Yumbel' },
        { id: '1130', name: 'Alto Biobío' },
    ],
    '12': [ // La Araucanía
        { id: '1201', name: 'Temuco' },
        { id: '1202', name: 'Padre Las Casas' },
        { id: '1203', name: 'Villarrica' },
        { id: '1204', name: 'Pucón' },
        { id: '1205', name: 'Loncoche' },
        { id: '1206', name: 'Nueva Imperial' },
        { id: '1207', name: 'Carahue' },
        { id: '1208', name: 'Saavedra' },
        { id: '1209', name: 'Teodoro Schmidt' },
        { id: '1210', name: 'Toltén' },
        { id: '1211', name: 'Gorbea' },
        { id: '1212', name: 'Lautaro' },
        { id: '1213', name: 'Perquenco' },
        { id: '1214', name: 'Galvarino' },
        { id: '1215', name: 'Traiguén' },
        { id: '1216', name: 'Lumaco' },
        { id: '1217', name: 'Purén' },
        { id: '1218', name: 'Angol' },
        { id: '1219', name: 'Collipulli' },
        { id: '1220', name: 'Curacautín' },
        { id: '1221', name: 'Ercilla' },
        { id: '1222', name: 'Lonquimay' },
        { id: '1223', name: 'Los Sauces' },
        { id: '1224', name: 'Lumaco' },
        { id: '1225', name: 'Renaico' },
        { id: '1226', name: 'Victoria' },
        { id: '1227', name: 'Curarrehue' },
        { id: '1228', name: 'Pitrufquén' },
        { id: '1229', name: 'Freire' },
        { id: '1230', name: 'Pitrufquén' },
        { id: '1231', name: 'Vilcún' },
        { id: '1232', name: 'Cunco' },
        { id: '1233', name: 'Melipeuco' },
        { id: '1234', name: 'Curarrehue' },
    ],
    '13': [ // Los Ríos
        { id: '1301', name: 'Valdivia' },
        { id: '1302', name: 'La Unión' },
        { id: '1303', name: 'Río Bueno' },
        { id: '1304', name: 'Lago Ranco' },
        { id: '1305', name: 'Panguipulli' },
        { id: '1306', name: 'Paillaco' },
        { id: '1307', name: 'Futrono' },
        { id: '1308', name: 'Mariquina' },
        { id: '1309', name: 'Lanco' },
        { id: '1310', name: 'Máfil' },
        { id: '1311', name: 'Corral' },
        { id: '1312', name: 'Los Lagos' },
    ],
    '14': [ // Los Lagos
        { id: '1401', name: 'Puerto Montt' },
        { id: '1402', name: 'Puerto Varas' },
        { id: '1403', name: 'Osorno' },
        { id: '1404', name: 'Castro' },
        { id: '1405', name: 'Ancud' },
        { id: '1406', name: 'Quellón' },
        { id: '1407', name: 'Calbuco' },
        { id: '1408', name: 'Fresia' },
        { id: '1409', name: 'Frutillar' },
        { id: '1410', name: 'Llanquihue' },
        { id: '1411', name: 'Los Muermos' },
        { id: '1412', name: 'Puerto Octay' },
        { id: '1413', name: 'Purranque' },
        { id: '1414', name: 'Puyehue' },
        { id: '1415', name: 'Queilén' },
        { id: '1416', name: 'Quellón' },
        { id: '1417', name: 'Quemchi' },
        { id: '1418', name: 'Quinchao' },
        { id: '1419', name: 'Río Negro' },
        { id: '1420', name: 'San Juan de la Costa' },
        { id: '1421', name: 'San Pablo' },
        { id: '1422', name: 'Chaitén' },
        { id: '1423', name: 'Futaleufú' },
        { id: '1424', name: 'Hualaihué' },
        { id: '1425', name: 'Palena' },
        { id: '1426', name: 'Cochamó' },
        { id: '1427', name: 'Maullín' },
        { id: '1428', name: 'Dalcahue' },
        { id: '1429', name: 'Curaco de Vélez' },
        { id: '1430', name: 'Puqueldón' },
    ],
    '15': [ // Aysén
        { id: '1501', name: 'Coyhaique' },
        { id: '1502', name: 'Puerto Aysén' },
        { id: '1503', name: 'Chile Chico' },
        { id: '1504', name: 'Cochrane' },
        { id: '1505', name: 'O\'Higgins' },
        { id: '1506', name: 'Tortel' },
        { id: '1507', name: 'Guaitecas' },
        { id: '1508', name: 'Río Ibáñez' },
        { id: '1509', name: 'Cisnes' },
        { id: '1510', name: 'Aysén' },
    ],
    '16': [ // Magallanes
        { id: '1601', name: 'Punta Arenas' },
        { id: '1602', name: 'Puerto Natales' },
        { id: '1603', name: 'Porvenir' },
        { id: '1604', name: 'Primavera' },
        { id: '1605', name: 'Timaukel' },
        { id: '1606', name: 'Cabo de Hornos' },
        { id: '1607', name: 'Antártica' },
        { id: '1608', name: 'Laguna Blanca' },
        { id: '1609', name: 'Río Verde' },
        { id: '1610', name: 'San Gregorio' },
        { id: '1611', name: 'Torres del Paine' },
    ]
};

export interface Location {
  id: string;
  name: string;
}

export async function getRegions(): Promise<Location[]> {
  // Simulate an API call
  return Promise.resolve(regions);
}

export async function getCommunesByRegion(regionId: string): Promise<Location[]> {
  // Simulate an API call
  return Promise.resolve(communesByRegion[regionId] || []);
}
