export enum PropertyStatus {
  REQUEST = 'REQUEST',
  PRE_APPROVED = 'PRE-APPROVED',
  PUBLISHED = 'PUBLISHED',
  INACTIVE = 'INACTIVE',
  SOLD = 'SOLD',
  RENTED = 'RENTED',
  CONTRACT_IN_PROGRESS = 'CONTRACT-IN-PROGRESS',
}
